jiva-w:
  image: paulohms/jivaw:3.19.13
  restart: always
  environment:
    - IP_BD_JIVAW=${ip_bd}
    - PORTA_BD_JIVAW=${porta_bd}
    - SID_BD_JIVAW=${sid_bd}
    - USUARIO_BD_JIVAW=${usuario_bd}
    - SENHA_BD_JIVAW=${senha_bd}
    - PACOTE_JIVAW=jiva-w_3.20b67.pkg
  command: ["/bin/sh","-c", "java -jar /opt/DPM/docker-package-manager.jar && sleep 2 && /opt/jboss_producao/bin/./jboss_init_redhat.sh start -Djape.lazy.init=true -Djape.lob.fields.as.lazy=true -Djape.ignore.ligacao.inconsistente=true && sleep 2 && tail -F /opt/jboss_producao/server/default/log/server.log"]
  links:
    - sas
#  volumes: 
#    - /opt/dados/{{ .Stack.Name }}/impressao/:/home/mgeweb/impressao # Modelos de Impressão
#    - /opt/dados/{{ .Stack.Name }}/repositorio/:/home/mgeweb/repositorio # Repositório de arquivos
#    - /opt/dados/{{ .Stack.Name }}/logs/:/opt/jboss_producao/server/default/log # logs do JBOSS
#    - /opt/dados/{{ .Stack.Name }}/certificados/:/opt/SanNFe # Certificados do SanNFe
#   # - /opt/dados/pkgs/:/home/mgeweb/sankhyaw-wpm/pkgs # Pkgs Jiva-W

sas:
  image: paulohms/sas:1.0
  restart: always
  environment:
    - IP_BD_JIVAW=${ip_bd}
    - PORTA_BD_JIVAW=${porta_bd}
    - SID_BD_JIVAW=${sid_bd}
    - USUARIO_BD_JIVAW=${usuario_bd}
    - SENHA_BD_JIVAW=${senha_bd}
    - IP_CONTAINER=${agent_ip}
  command: ["/bin/sh","-c", "java -jar /opt/DSM/docker-sas-manager.jar && sleep 2 & /opt/SAS*/bin/./run-sas.sh && sleep 2 && tail -f /opt/SAS*/log/server*.log"]

load-balancer:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - ${porta_load_balancer}:${porta_load_balancer}/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
